name: "Migration Checklist"
description: "Post the migration checklist"
author: "Miles McGuire <miles.mcguire@intercom.io>"

inputs:
  token:
    description: "Github Token"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.token }}

branding:
  icon: "mic"
  color: "purple"
